config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'products/example'

  get 'subproducts/example'

  get 'news/example'

  get 'news/content'

  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def example
  end

  def content
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  end

  def show
  end

  def example
  end

end

app/controllers/subproducts_controller.rb
class SubproductsController < ApplicationController

  def example
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_footer.html.erb
<div class="container-fluid">

  <section class='footer'>
    <div class="row">

        <nav class="navbar navbar-default navbar-static-bottom footer1">
          <div class="col-md-10 col-md-offset-1">
            <div class="col-md-2">
              <h4 class="text-left">ABOUT US</h4>
              <br>
              <p class="text-left about1"><%= link_to "Who We Are", pages_about_path %></p>
              <p class="text-left about2"><%= link_to "Contact Us", pages_contact_path %></p>
            </div>
            <div class="col-md-5">
              <h4 class="text-left">VONOX OIL</h4>
              <br>
              <p class="text-justify">Vinyl migas poutine banjo direct trade, everyday carry freegan biodiesel butcher forage beard etsy. Heirloom brunch banh mi, readymade ethical kale chips offal paleo fap tumblr. </p>
            </div>
            <div class="col-md-1">
            </div>
            <div class="col-md-4">
              <h4 class="text-left">OEM CERTIFICATE APPROVAL</h4>
              <br>
              <div class="row certi">
                <div class="col-md-6 certification">
                  <%= link_to image_tag('logo-eolcs.png', size: "69x83"), root_path %>
                </div>
                <div class="col-md-6 certification">
                  <%= link_to image_tag('logo-iso9001.png', size: "94x77"), root_path %>
                </div>
              </div>
            </div>
          </div>
        </nav>

    </div>
  </section>

  <section class="footer">
    <div class="row">
      <nav class="navbar-default navbar-static-bottom footer2">
        <div class="col-md-12 last">
          <p>Copyright © 2016. All Rights Reserved.</p>
        </div>
      </nav>
    </div>
  </section>

</div>

app/views/common/_left.html.erb
<div class="col-md-3">
  <br>
  <div class="row">
    <div class="col-md-11">
      <ul class="nav nav-pills nav-stacked nav-btn" style="max-width: 300px;">
        <li> <%= link_to("工業用油", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("車輛用油", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("金屬加工切削加工液", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("潤滑脂", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("防銹劑", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("預留一", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("預留二", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
        <li> <%= link_to("預留三", products_example_path,
                  class: "btn btn-sm btn-default") %> </li>
      </ul>
    </div>
    <div class="col-md-1">
    </div>
  </div>

  <br>

</div>

app/views/common/_navbar.html.erb
<div class="container-fluid">

  <div class="row">

    <nav class="navbar navbar-default navbar-custom">
      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><strong></strong></a>
      </div> -->
      <ul class="nav navbar-nav pull-right navbar-social">
        <li>
          <a href="https://google.com/" target="_blank">
            <p style="font-family: Helvetica Neue;font-size: 5px;"><i class="fa fa-google-plus"> Google+</i></p>
          </a>
       </li>
       <li>
          <a href="https://twitter.com/" target="_blank">
            <p style="font-family: Helvetica Neue;font-size: 5px;"><i class="fa fa-twitter"> Twitter</i></p>
          </a>
       </li>
       <li>
          <a href="https://www.facebook.com/" target="_blank">
            <p style="font-family: Helvetica Neue;font-size: 5px;"><i class="fa fa-facebook"> Facebook</i></p>
          </a>
       </li>
  <!--      <li>
          <a href="http://www.youtube.com/" target="_blank">
            <i class="fa fa-youtube"> Youtube</i>
          </a>
       </li> -->
       <!-- <li>
          <a href="https://twitter.com/" target="_blank">
            <i class="fa fa-envelope-o"> Email</i>
          </a>
       </li> -->
      </ul>
    </nav>
    <nav class="navbar navbar-default navbar-custom2">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><strong></strong></a>
        <%= link_to image_tag('1321-01.png', size: "270x81"), root_path %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right navbar-text">
          <li><div class="underscore"><%= link_to "HOME", root_path %></div></li>
          <li><div class="underscore"><%= link_to "COMPANY", pages_about_path %></div></li>
          <li class="dropdown">
            <div class="dropdown-underscore">
              <a onclick="myFunction()" class="dropbtn">PRODUCT<span class="caret"></span></a>
              <div class="dropdown-content" id="myDropdown">
                <%= link_to "工業用油", products_example_path %>
                <%= link_to "車輛用油", products_example_path %>
                <%= link_to "金屬加工切削加工液", products_example_path %>
                <%= link_to "潤滑脂", products_example_path %>
                <%= link_to "防銹劑", products_example_path %>
                <%= link_to "預留一", products_example_path %>
                <%= link_to "預留二", products_example_path %>
                <%= link_to "預留三", products_example_path %>
              </div>
            </div>
          </li>
          <li><div class="underscore"><%= link_to "NEWS", news_example_path %></div></li>
          <li><div class="underscore"><%= link_to "CONTACT US", pages_contact_path %></div></li>
        </ul>
      </div>
    </nav>
  </div>

</div>


<script>

//   $('.dropdown-toggle').dropdown()

/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vonox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">

  <style>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css"/>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
  </style>

</head>
<body>

  <div id="wrapper">

    <div id="header">
      <%= render "common/navbar" %>
    </div>

    <%= breadcrumbs pretext: "You are here: ", display_single_fragment: true, style: :bootstrap, separator: '' %>

    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">
      <%= render "common/footer" %>
    </div>

  </div>

  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
    async defer></script>


</body>
</html>

app/views/news/content.html.erb
<div class="container-fluid">
  <div class="row">

  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <%= render 'common/left' %>

      <div class="col-md-9" style="letter-spacing: 1px;">

        <div class="col-md-12">

          <div class="aboutline"></div>
          <h3>
            <strong>NEWS</strong>
          </h3>

          <br>

          <div class="row">

            <div class="col-md-8">
              <div class="pull-left">

                <h4>GManage risks to stay relevant</h4>

              </div>
            </div>

            <div class="col-md-4">
              <div class="pull-right">

                <h5>Posted : 17/03/2016</h5>

              </div>
            </div>

          </div>

          <br>

          <div class="row">

            <div class="col-md-3">
              <div class="pull-left">
                <%= image_tag ("sumi_special_projects-spring-united_oil-jacky_tan-4_adopting_best_practices 150x225.jpg") %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <p>In the second of a three-part series on capability development, April Chong speaks to an SME and an industry expert from the SME Capabilities Series of events about their views on growing new markets.</p>
              </div>
            </div>

          </div>



          <br>

        <%= link_to " << Back", news_example_path, class: "btn btn-link" %>

        </div>

      </div>
    </div>
  </div>
</div>

<br>
<br>

app/views/news/example.html.erb
<div class="container-fluid">
  <div class="row">

  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <%= render 'common/left' %>

      <div class="col-md-9" style="letter-spacing: 1px;">

        <div class="col-md-12">

          <div class="aboutline"></div>
          <h3>
            <strong>NEWS</strong>
          </h3>

          <%= render "pagination" %>

          <div class="row">
            <div class="col-md-12">

              <div class="col-md-3">
                <div class="pull-left">
                  <%= image_tag ("sumi_special_projects-spring-united_oil-jacky_tan-4_adopting_best_practices 150x225.jpg"), size: "150x160" %>
                </div>
              </div>
              <div class="col-md-9 product-content">
                <div class="pull-right">
                  <h4><%= link_to "GManage risks to stay relevant", "#", class: "product-name" %></h4>
                  <p>In the second of a three-part series on capability development, April Chong speaks to an SME and an industry expert from the SME Capabilities Series of events about their views on growing new markets. </p>

                  <p>
                    <%= link_to "View Detail", news_content_path %>
                  </p>
                </div>
              </div>

            </div>
          </div>

          <br>

          <div class="row">
            <div class="col-md-12">

              <div class="col-md-3">
                <div class="pull-left">
                  <%= image_tag ("KR Post Mid.jpg"), size: "150x160" %>
                </div>
              </div>
              <div class="col-md-9 product-content">
                <div class="pull-right">
                  <h4><%= link_to "Korea - United Infinite fully synthetic engine oils gaining popularity", "#", class: "product-name" %></h4>
                  <p>Range of United Products now available in 300 workshops.</p>

                  <p>
                    <%= link_to "View Detail", news_content_path %>
                  </p>
                </div>
              </div>

            </div>
          </div>

          <br>

          <div class="row">
            <div class="col-md-12">

              <div class="col-md-3">
                <div class="pull-left">
                  <%= image_tag ("CNOOC Website Banners.jpg"), size: "150x160" %>
                </div>
              </div>
              <div class="col-md-9 product-content">
                <div class="pull-right">
                  <h4><%= link_to "MAN Diesel & Turbo (MDT) has No Objection to UniMar 570 Cylinder Oil", "#", class: "product-name" %></h4>
                  <p>MAN Diesel & Turbo (MDT) tested basic additive package of cylinder oil, CNOOC Unimar 570, 70 BN, SAE 50. The test found Unimar 570 acceptable. </p>

                  <p>
                    <%= link_to "View Detail", news_content_path %>
                  </p>
                </div>
              </div>

            </div>
          </div>

        <br>

        <%= render "pagination" %>

        </div>

      </div>
    </div>
  </div>
</div>

<br>
<br>

app/views/pages/_thumbnails.html.erb
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('cars.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "工業用油", products_example_path, class: "caption-title" %></h4>
            <p>Locavore drinking vinegar 8-bit chartreuse. Craft beer artisan.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('trucks.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "車輛用油", products_example_path, class: "caption-title" %></h4>
            <p>Narwhal chillwave VHS venmo normcore, chartreuse forage vegan hoodie.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('motorcycles.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "金屬加工切削加工液", products_example_path, class: "caption-title" %></h4>
            <p>3 wolf moon whatever street art, banjo cronut poutine asymmetrical.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('trucks-2.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "潤滑脂", products_example_path, class: "caption-title" %></h4>
            <p>Butcher +1 etsy mumblecore, authentic marfa four dollar toast man.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('MFW Home.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "防銹劑", products_example_path, class: "caption-title" %></h4>
            <p>Narwhal aesthetic stumptown, pork belly +1 green juice knausgaard meh.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('united-oil.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "預留一", products_example_path, class: "caption-title" %></h4>
            <p>Hammock biodiesel seitan, tacos taxidermy vice offal sartorial keffiyeh.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('cars.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "預留二", products_example_path, class: "caption-title" %></h4>
            <p>Master cleanse asymmetrical intelligentsia cronut tote bag bushwick.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag('motorcycles.jpg'), products_example_path %>
          <div class="caption caption_box">
            <h4><%= link_to "預留三", products_example_path, class: "caption-title" %></h4>
            <p>Narwhal aesthetic stumptown, pork green juice knausgaard meh pickled.</p>
            <%= link_to "", root_url, class: "flaticon-shape icon" %>
          </div>
        </div>
      </div>

app/views/products/example.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="display:block;text-align: center">
      <%= image_tag ("premium_oil.jpg"), style:"width:952;height:auto;left:0;" %>
    </div>



    <br>

  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <% breadcrumb :product, @product %>

      <div class="col-md-3">
        <br>
        <div class="row">
          <div class="col-md-11">
            <ul class="nav nav-pills nav-stacked nav-btn" style="max-width: 300px;">
              <li> <%= link_to("工業用油", products_example_path,
                        class: "btn btn-sm btn-default btn-current") %> </li>
              <li> <%= link_to("車輛用油", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("金屬加工切削加工液", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("潤滑脂", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("防銹劑", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("預留一", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("預留二", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("預留三", products_example_path,
                        class: "btn btn-sm btn-default") %> </li>
            </ul>
          </div>
          <div class="col-md-1">
          </div>
        </div>

        <br>

      </div>

      <div class="col-md-9" style="letter-spacing: 1px;">

        <div class="col-md-12">

          <div class="aboutline"></div>
          <h3>
            <strong>工業用油</strong>
          </h3>

          <p>To meet the demands for racing and extreme applications, we formulate this range with the most advanced components & latest technology. The range uses synthetic base oils which has naturally high viscosity index & superior thermo-stability and meet highest API (American Petroleum Institute) specifications API SN. Performance has been proven with success at race events in Australia, Macau, Malaysia and China. </p>

          <br>

        </div>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= link_to (image_tag ("GX_racing.jpg"), size: "150x199"), subproducts_example_path %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4><%= link_to "GX RACING", subproducts_example_path, class: "product-name" %></h4>
                <p>Fully Synthetic SAE 5W40 meets API SN with PAO – Formulated with PAO (Poly Alpha Olefins) with the latest development in lubricating oil technology to maximize the protection for the new engines. Exceeds most demanding requirements of modern engine’s emission control, oil consumption & fuel savings. Uses effective friction reduction and load improvement agents. Especially suited for a sport driving styles and turbo charged engines running at higher temperatures.</p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= link_to (image_tag ("f1_experience.jpg"), size: "150x199"), subproducts_example_path %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4><%= link_to "F1 EXPERIENCE", subproducts_example_path, class: "product-name" %></h4>
                <p>United F1 Experience SAE 5W30 API SN is a top tier low SAPS 100% Fully Synthetic Motor Oil delivers the latest development in lubricating oil technology to maximize the protection for the newest gasoline engine meeting ACEA C3-10 Standard.</p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= link_to (image_tag ("GD1.jpg"), size: "150x199"), subproducts_example_path %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4><%= link_to "GD1 5W40", subproducts_example_path, class: "product-name" %></h4>
                <p>United GD1 SAE 5W40 API SN/SM/CF Fully Synthetic Engine Oil is ideal for modern high output, low emission, super or turbo charged, DOHC or GDI engines with anti-oxidation property that are commonly found in latest European and Japanese models.</p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= link_to (image_tag ("GD2.jpg"), size: "150x199"), subproducts_example_path %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4><%= link_to "GD2 5W50", subproducts_example_path, class: "product-name" %></h4>
                <p>United GD2 SAE 5W50 API SN/SM/CF Fully Synthetic Engine Oil is blended from a synthesis of special basestock processed by a patented technology. Reinforced with a powerful additive package, United GD2 is ideal for modern high output, low emission, super or turbo charged, DOHC or GDI engines that are commonly found in latest European and Japanese models.</p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= link_to (image_tag ("M2.jpg"), size: "150x199"), subproducts_example_path %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4><%= link_to "M2 UNIQUE SERIES", subproducts_example_path, class: "product-name" %></h4>
                <p>United M2 Unique API SN/SM Synthetic Engine Oil is a premium fuel-efficient engine oil, specially designed for use in gasoline and diesel car engines, and in particular for Volkswagen TDI direct injection engine fitted with pump injector.</p>
              </div>
            </div>

          </div>
        </div>

        <br>

      </div>
    </div>
  </div>
</div>

<br>
<br>

app/views/subproducts/example.html.erb
<div class="container-fluid">
  <div class="row">
    <div style="display:block;text-align: center">
      <%= image_tag ("gold.jpg"),style:"width:952;height:auto;left:0;" %>
    </div>

    <br>

  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-3">
        <br>
        <div class="row">
          <div class="col-md-11">
            <ul class="nav nav-pills nav-stacked nav-btn" style="max-width: 300px;">
              <li> <%= link_to("GOLD", subproducts_example_path,
                        class: "btn btn-sm btn-default btn-current") %> </li>
              <li> <%= link_to("PLUS", subproducts_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("XTG", subproducts_example_path,
                        class: "btn btn-sm btn-default") %> </li>
              <li> <%= link_to("OTHERS", subproducts_example_path,
                        class: "btn btn-sm btn-default") %> </li>
            </ul>
          </div>
          <div class="col-md-1">
          </div>
        </div>

        <br>

      </div>

      <div class="col-md-9" style="letter-spacing: 1px;">

        <div class="col-md-12">

          <div class="aboutline"></div>
          <h3>
            <strong>GOLD RANGE</strong>
          </h3>

          <p>Fully synthetic with advanced additives for maximum performance </p>

          <br>

        </div>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= image_tag ("gold_series.jpg"), size: "150x199" %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4>GOLD SERIES</h4>
                <p>United Gold Fully Synthetic Engine Oil meets highest API SN/SM/CF for gasoline engine. It is blended from a synthesis of special basestock processed by a patented technology. Reinforced with a powerful additive package, United Gold is ideal for modern high output, low emission, super or turbo charged, DOHC or GDI engines that are commonly found in latest European and Japanese models. With a natural High Viscosity Index and low volatility, United Gold offers high performances, uncompromised protection to the engines.</p>
                <p>
                  <%= link_to "View Detail", "#" %>
                </p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= image_tag ("gold_pro_c4.jpg"), size: "150x199" %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4>GOLD PRO C4</h4>
                <p>United Gold Pro C4 is a top Tier low SAPS passenger car lubricant that is blended with premium fully synthetic base oil incorporating with advanced technology additives to provide excellent low temperature soot dispersancy and outstanding high temperature deposit control. It is designed for use in high performance gasoline and light duty diesel engines meeting ACEA C4-10 and Renault RN0720 that are suitable for Euro IV & V engines where after-treatment such as Diesel Particulate Filters (DPFs) and Three Way Catalysts (TWC) are used.</p>
                <p>
                  <%= link_to "View Detail", "#" %>
                </p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= image_tag ("gold_vx.jpg"), size: "150x199" %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4>GOLD VX</h4>
                <p>United Gold VX is a premium quality “Mid SAPS” passenger car lubricants that specifically formulated with ultimate active clean technology. It is blended with high quality Polyalphaolefins (PAO) base fluid and the high technology core additive package that meets the requirements of ACEA C3 and MB-Approval 229.51. It is suitable for use in the widest range of modern Passenger Cars and small vehicles include Gasoline vehicles as well.</p>

                <p>United Gold VX provides high temperature protection, exceeding the tough standards against thermal breakdown. It can dramatically reduce the carbon deposit from building up on engine surfaces while protecting sensitive exhaust gas treatment systems.</p>

                <p>
                  <%= link_to "View Detail", "#" %>
                </p>
              </div>
            </div>

          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">

            <div class="col-md-3">
              <div class="pull-left">
                <%= image_tag ("gold_lh.jpg"), size: "150x199" %>
              </div>
            </div>
            <div class="col-md-9 product-content">
              <div class="pull-right">
                <h4>GOLD LH</h4>
                <p>United Gold LH is a fully synthetic passenger car motor oil (PCMO) especially developed for the requirements of Ford WSS-M2C925-B specification. It meets the requirements of ACEA European sequence A1/B1-10 requirements for low friction, low viscosity lubricants for gasoline and light diesel engines.</p>
                <p>
                  <%= link_to "View Detail", "#" %>
                </p>
              </div>
            </div>

          </div>
        </div>

        <br>

      </div>
    </div>
  </div>
</div>

<br>
<br>